spring.application.name=ats
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ats_system?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:chirag}
spring.datasource.password=${DB_PASSWORD:boliwal}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never
server.port=8080
